run:
  timeout: 5m

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

linters-settings:
  deprecated:
    enabled: false
  enable:
    - unused

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unconvert
    - unparam
    - gosimple
    - ineffassign
    - unused
    - typecheck
